### ISSUE TITLE
Feedback from Sean McKay

### ISSUE THREAD

**Issue by sean-m-mckay** [UBC-MDS/DSCI-532_2024_5_HomeScope#83]
1. I like that you included a graph that shows the distribution of house prices for a given city. It might be nice to have the scale in absolute units (Number of properties) rather than density, as it gives an idea of the overall size of the housing market, and is more intuitive
2. I found the comparison chart a bit unintuitive to use. Since these are just individual values, it doesn't seem to make sense to include a chart comparing them (It makes a bit more sense with multiple cities - but a better choice of graph would be a scatter plot with field 1 is on the x-axis, field 2 on the y-axis, with points for each city - this helps show if there is an underlying relationship between the variables in different cities).
3. Very minor, but the "Top 5 bedroom/bathroom chart" I found a bit confusing - It might be better to title it "Bedroom / Bathroom counts across cities", and potentially have a category for 5+ bedrooms rather than limiting it to the "Top 5"
4. I really like the cohesive design and the cards at the top - It would be nice to display which neighbourhood the minimum and maximum priced houses are located in, when you select more than one city
5. The GeoChart is a great feature, it would be nice to potentially colour the cities based on the mean income, to give a visual representation of the differences - Also since the chart is the only one which is unaffected by the global filters, it might make sense to visually separate it from the other graphs. And finally, super minor but when you select Ontario, there is a bubble in the Geospatial chart for "Nanaimo", which is in BC - maybe this is an underlying data issue?

**Comment by carrieyanyi** [comment]
Thank you for reviewing our dashboard!
Here are some areas that addressing your feedback:
- Our choice for using density instead of absolute unit is based on the instructor's suggestion since we need to compare several cities at once. Density, as recommended, could be helpful in this case.
- We removed the scatter plot and replaced it with a bar chart.
- We changed the bar chart title to make more sense.
- We adjusted the calculation behind showing the Card results, and change the value to average population and income.
- We fixed the map to only show selected cities.
