### ISSUE TITLE
Milestone4 - Feedback addressing from peer and instructor

### ISSUE THREAD

**Issue by iris0614** [UBC-MDS/DSCI-532_2024_5_HomeScope#84]

**Comment by Aishwarya120111** [comment]
**Feedback 1:** 
Overall, the dashboard looks pretty good! It excels in providing a rich, interactive user experience with a clean and professional design that facilitates easy navigation through different data insights. The inclusion of a map for geographical visualization is particularly impressive, as it allows users to understand the spatial distribution of property values at a glance. Moreover, the interactive filters are a strong feature that empower users to tailor the data analysis to their specific needs and interests. This level of customization is invaluable for stakeholders looking to make informed decisions. Additionally, the bar plot juxtaposing Price with Median Family Income is an excellent example of comparative analysis, enabling users to quickly assess key market indicators.
Intuitiveness and User Guidance.

To make the dashboard even better, here are some aspects that could be improved:

1. User Guidance: The dashboard contains a wealth of information, which is great for detailed analysis. However, for new users or those less familiar with data analysis, it may be overwhelming. Including a brief tutorial or guided tour of the dashboard features upon first visit could improve user experience by providing context for what they're viewing and how to interact with the data.
2. Data Visualization and Accessibility: The scatter plots (Price-Bedroom Correlation and Price-Bathroom Correlation) have points that are quite dense in some areas. Consider implementing a feature like zooming or hover-over tooltips that display more information about each point. This would allow users to more easily interpret specific data points in crowded plots.  -- **We fixed it**
3. Contrast and Legibility: The bar plot comparing Price and Median Family Income might benefit from enhanced contrast or a different color scheme. The blue for Price is quite strong compared to the red for Median Family Income, which could make it a bit difficult for users with visual impairments or color blindness to interpret the graph effectively. --- **We are not picking it up**
4. Layout and Design: The layout is quite linear and requires significant scrolling, which might cause users to miss out on important information at the bottom if they don't scroll all the way down. Organizing content into tabs or having a side navigation bar for different sections could streamline the user experience and ensure all information is easily accessible. --- **We can zoom out**
5. Big Picture — Market Dynamics and Predictive Insights: While the dashboard does an excellent job at presenting current and historical data, it could be enhanced by integrating predictive analytics. Since the target audience includes investors and market analysts, providing forward-looking insights based on market trends could be invaluable. This could include predictive models for price trends or a feature that simulates how changes in market variables might affect property values. --- **We cannot predict**

**Feedback 2:**
The overall view of the dashboard is fantastic. It effectively communicates its intended message, and the information provided is detailed and easy to interpret. However, I have noticed a few small details that could enhance the dashboard even further.
If you could locate the GeoJson file, using the Choropleth Maps might be more beneficial than heatmaps. Choropleth Maps would more clearly represent the boundaries for each city, as using a single point can be challenging to discern.  -- **Its too complex with our dataset**
Adding a brief description next to the title could help clarify the content, as it is somewhat difficult to understand based solely on the title.  ---**We have fixed it**
Would it be possible to separate these plots with dividers or use the Card component? This might improve the visual organization.  --- **Its not useful**
I would recommend using a consistent color scale across all plots, if feasible. -- **We have fixed it**
Could you modify the hover content for the bedroom distribution? The current use of x, y, and text is a bit confusing.   ---- **We can pick this up**

**Feedback 3:**
Is the app overall well-suited to the usage scenario and target audience?
I think this dashboard was well-suited to the usage scenario and target audience. It contains the necessary information for their users (real estate investors, developers, market analysts, or urban planner) to assess the housing investment market.
Do you see some ways that the dashboard could be extended to better cater to the target audience or meet the specifications in the usage scenario?
I think since one of the metrics used is median family income, it would make more sense to compare this to median price instead of average in the barplot.
I thought the price distribution chart and summary statistics were very useful!
Was the app intuitive to use? Did it behave as you expected?
Overall I think the dashboard was intuitive. However, the first barplot with the two axis may be confusing to the user audience, since it looked like median income was larger than average price at first glance. I think this can be useful for provinces that have more than one city, but less so when there is only one city selected. I would suggest adding more cities to the default value so that it automatically displays with multiple values to compare.
I also noticed was that when Newfoundland and Labrador is selected the city defaults to Nanaimo, BC, which is what then shows on the map. It seemed to work correctly for other input values.
Can you think of other alternatives or improvements for the plots regarding the selection of the plots or how they are set up to reach to the widgets?
I think the instructions for selecting the bar chart filters on the left-hand side could be improved. Instead of saying "Bar Plot First Variable", "Bar Plot Second Variable" and "Bar Plot Third Variable" it could say "Bar Plot First Axis Variable", "Bar Plot Second Axis Variable" and "Bottom Bar Plot Variable". Or the dropdown for the bottom plot could be put directly above the chart.   --- **This has been addressed**
Are the plots or other outputs sufficiently described / intuitive enough for the target audience? 
Yes, I think the titles describe the plots well and are easy to interpret. However, for the price variable of the barplots I think including the summary metric would help with clarity, eg. "Average Price".

**Feedback 4:**
I like that you included a graph that shows the distribution of house prices for a given city. It might be nice to have the scale in absolute units (Number of properties) rather than density, as it gives an idea of the overall size of the housing market, and is more intuitive
I found the comparison chart a bit unintuitive to use. Since these are just individual values, it doesn't seem to make sense to include a chart comparing them (It makes a bit more sense with multiple cities - but a better choice of graph would be a scatter plot with field 1 is on the x-axis, field 2 on the y-axis, with points for each city - this helps show if there is an underlying relationship between the variables in different cities).
Very minor, but the "Top 5 bedroom/bathroom chart" I found a bit confusing - It might be better to title it "Bedroom / Bathroom counts across cities", and potentially have a category for 5+ bedrooms rather than limiting it to the "Top 5"
I really like the cohesive design and the cards at the top - It would be nice to display which neighborhood the minimum and maximum priced houses are located in, when you select more than one city   --- **this makes sense we can pick it up**
The GeoChart is a great feature, it would be nice to potentially color the cities based on the mean income, to give a visual representation of the differences - Also since the chart is the only one which is unaffected by the global filters, it might make sense to visually separate it from the other graphs. And finally, super minor but when you select Ontario, there is a bubble in the Geospatial chart for "Nanaimo", which is in BC - maybe this is an underlying data issue?   --- **We can fix this**

**Comment by Aishwarya120111** [comment]
1. I really like the cohesive design and the cards at the top - It would be nice to display which neighborhood the minimum and maximum priced houses are located in, when you select more than one city --- @nassimgh9 
2. Could you modify the hover content for the bedroom distribution? The current use of x, y, and text is a bit confusing.  --- @carrieyanyi 
3. Add a table to show the price according to filters --- @iris0614 
4. Highlight the cities in map based on the selection --- @Aishwarya120111 
5. Remove the y label of density plot and  Update the layout according to the new change and  Change the default to two cities---@iris0614
